AWSTemplateFormatVersion: '2010-09-09'
Resources:
  MyVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.10.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      InstanceTenancy: default
  
  PrivateSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: 1a
      VpcId: !Ref MyVPC
      CidrBlock: 10.10.100.10/24
      Tags:
        - Key: type
          Value: private-environment
  
    PrivateSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: 1b
      VpcId: !Ref MyVPC
      CidrBlock: 10.10.100.20/24
      Tags:
        - Key: type
          Value: private-environment